### ISSUE TITLE
Typo error in bert_nlu_basic_api.py

### ISSUE THREAD

**Issue by Rishabbh-Sahu** [MahmoudWahdan/dialog-nlu#26]
there is a typo in line number 30. 
        if type_ == 'albert':
It should be 
        if type_ == 'bert':

Creating a PR for this small error will not make sense hence creating an issue. 

Thanks

**Comment by MahmoudWahdan** [comment]
Thanks @Rishabbh-Sahu 
Fixed 193f4d543b4f751051eb6507f4a934a4b3a217d0
