### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by manojpreveen** [MahmoudWahdan/dialog-nlu#28]
I'm getting this error when I tried to run the script for training after building the library :
ModuleNotFoundError: No module named 'dialognlu.models'

Checked the contents of dialognlu library that got installed and found just these files : 
1. __init.py__
2. __pycache__  
3. auto_nlu.py  
4. compression  
5. nlu_components.py  
6. utils

Is there a problem while building the library or Am I doing something wrong here?
Please help.

**Comment by MahmoudWahdan** [comment]
Hi @tromedlov22 
My bad I was testing on editable mode ```pip install -e .```
The problem that I forgot the __init__.py in some packages.
Now it is fixed eb6bbcea462c52f8ce9e6a99b0f7ae0076a44756
Please, try and let me know to close the issue. ```pip install .```

**Comment by manojpreveen** [comment]
Yeah the above issue is resolved, but came across this : 

File "/usr/local/share/anaconda3/envs/tfn/lib/python3.7/site-packages/dialognlu/nlu_components.py", line 86, in train
    max_length = self.text_vectorizer.max_length
AttributeError: 'BERTVectorizer' object has no attribute 'max_length'

Checked BERTVectorizer class and there's no attribute max_length which is being referred to in line 86 of nlu_components.py

**Comment by MahmoudWahdan** [comment]
Hi @tromedlov22 
Yes, it was missing in `BERTVectorizer`
Fixed now 1e84dd0670d3f22ab07b965723bb4b81c49a7499 and tested
Please, check and let me know.

**Comment by MahmoudWahdan** [comment]
Hi @tromedlov22  Please, let me know if it worked with you.
Thanks.

**Comment by manojpreveen** [comment]
Sorry for the delay, will test it out completely this weekend and will close the issue.
Thanks.

**Comment by manojpreveen** [comment]
Looks good to me for now. Closing the issue. Will raise new issue if I face any.
