### ISSUE TITLE
Upgrade to TF 2

### ISSUE THREAD

**Issue by jvence** [MahmoudWahdan/dialog-nlu#3]
Any plans to upgrade this to TF2? 
And perhaps implement some sort of Estimator and/or serving support.
Many thanks.

**Comment by MahmoudWahdan** [comment]
Thanks for your suggestions.
Yes, We will add TF2 support soon and may be some kind of rest API

**Comment by MahmoudWahdan** [comment]
A simple rest service added

**Comment by jvence** [comment]
That is great news. Thank you.

**Comment by MahmoudWahdan** [comment]
TF 2 support merged with master  
73b3134

**Comment by jvence** [comment]
Thanks so much. Will test and get back to you.
