### ISSUE TITLE
unexpected keyword argument 'use_cdn' error

### ISSUE THREAD

**Issue by deathsurgeon1** [MahmoudWahdan/dialog-nlu#35]
/usr/local/lib/python3.6/dist-packages/dialognlu/compression/commons.py in from_pretrained_detailed(model_class, pretrained_model_name_or_path, *model_args, **kwargs)
    160                 pretrained_model_name_or_path,
    161                 filename=(WEIGHTS_NAME if from_pt else TF2_WEIGHTS_NAME),
--> 162                 use_cdn=use_cdn,
    163             )
    164 

TypeError: hf_bucket_url() got an unexpected keyword argument 'use_cdn'

**Comment by MahmoudWahdan** [comment]
Hi @deathsurgeon1 please, share the code you used and your system version, tensorflow version, and python version.

**Comment by deathsurgeon1** [comment]
> Hi @deathsurgeon1 please, share the code you used and your system version, tensorflow version, and python version.

I imported in google colab and ran the sample code that you have provided in your repo readme. It was running fine till yesterday

**Comment by MahmoudWahdan** [comment]
Hi @deathsurgeon1 The error show is related to getting/downloading pretrained transformers model. I'll check on my side and let you know.

**Comment by MahmoudWahdan** [comment]
Hi @deathsurgeon1 
The reason of the bug is that transformers library had a new release yesterday, now it is v3.5.0.
We have a copied part related to downloading the pretrained model. This code part is used in layer-pruning feature.
Now it is fixed 9599cff8c2f03ae85bdb4ab3a009a803f26269d9
Please, pull latest and verify.
If it works for you, then close the issue.

Thanks.

**Comment by deathsurgeon1** [comment]
> Hi @deathsurgeon1
> The reason of the bug is that transformers library had a new release yesterday, now it is v3.5.0.
> We have a copied part related to downloading the pretrained model. This code part is used in layer-pruning feature.
> Now it is fixed [9599cff](https://github.com/MahmoudWahdan/dialog-nlu/commit/9599cff8c2f03ae85bdb4ab3a009a803f26269d9)
> Please, pull latest and verify.
> If it works for you, then close the issue.
> 
> Thanks.

it seems working fine now
