### ISSUE TITLE
Can not import BertCrfNLU

### ISSUE THREAD

**Issue by zeinabfarhoudi** [MahmoudWahdan/dialog-nlu#38]
Hi, 
after I import BertCrfNLU, I can't train with this module.
would you please fix the problem

**Comment by MahmoudWahdan** [comment]
Hi @farhodi 
Bug fixed as in  1421d28ecdc3ccb1d1f08ef736f37ea1592abc69 
Please, pull latest and let me know if it works with you.

**Comment by zeinabfarhoudi** [comment]
Hi @MahmoudWahdan , 
Thanks for your response. I get the latest one, but when I run BertCrfNLU to train the model, I face a memory leak error.
I run the code in colab with TPU running mode. When I run to train the model, after displaying the summary of the model and before the first epoch training model begins, my session drop because of lack of memory!

**Comment by MahmoudWahdan** [comment]
Hi @farhodi 
Could you please put the code and error here?
How much data do you have?

**Comment by MahmoudWahdan** [comment]
Hi @farhodi 
Did you get the chance to check this notebook https://github.com/MahmoudWahdan/dialog-nlu/blob/master/notebooks/using_bert_crf_nlu.ipynb
