### ISSUE TITLE
Determining confidence level for intent prediction

### ISSUE THREAD

**Issue by jvence** [MahmoudWahdan/dialog-nlu#4]
Is there anyway to figure out the confidence level for an intent prediction? Often the system will return an Intent that is inaccurate (for different reasons of course) so it would be nice to get an accuracy reading for each prediction.

**Comment by MahmoudWahdan** [comment]
Kindly, note that the repo is originally for SOTA in dialog NLU researches, so it is not supported.
But, We can add it in the future.
I'll leave your suggestion open until I add the feature.
Thanks for your suggestions :)

**Comment by MahmoudWahdan** [comment]
Feature added 
@jvence please, check
