### ISSUE TITLE
islamic dataset

### ISSUE THREAD

**Issue by MuhammadHusban** [MahmoudWahdan/dialog-nlu#40]
Assalam o Alaikum brother i need islamic questions and answers dataset can u provide me?

**Comment by MahmoudWahdan** [comment]
Walikom alsalam bro,
Actually, I didn't work on one before, but I use Masader (https://arbml.github.io/masader/) to find Arabic datasets. They did a great effort on indexing almost all Arabic datasets with many metadata fields including "Access". Please, feel free to have a look there.
Thanks.
